ktor:
  application:
    modules:
      - com.example.ApplicationKt.module
  deployment:
    port: 8080
  database:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/jpastuff"
    user: "postgres"
    password: "YOUR_PASSWORD"
postgres:
  url: "jdbc:postgresql://localhost:5432/jpastuff"
  user: "postgres"
  password: "YOUR_PASSWORD"